CREATE TABLE [dbo].[Table1]
(
	[Id] SMALLINT NOT NULL PRIMARY KEY,
	[GUId] NVARCHAR(50) NOT NULL , 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [InternalName] NVARCHAR(MAX) NOT NULL, 
    [URL] NVARCHAR(MAX) NOT NULL 
)
